[phases.setup]
nixPkgs = ['nodejs_18', 'yarn', 'pkg-config']

[phases.install]
cmds = [
  'bundle install',
  'yarn install'
]

[phases.build]
cmds = [
  'bundle exec rails assets:precompile'
]

[start]
cmd = 'bundle exec rails server -b 0.0.0.0 -p $PORT'

[variables]
RAILS_ENV = 'production'
NODE_ENV = 'production'
RAILS_SERVE_STATIC_FILES = 'true'
RAILS_LOG_TO_STDOUT = 'true'
